---
language: bash
sudo: required
dist: trusty

install:
- echo "deb http://archive.ubuntu.com/ubuntu yakkety main universe" | sudo tee /etc/apt/sources.list.d/ubuntu-yakkety.list
- sudo apt-get update -qq
- sudo apt-get install -y -t yakkety packer

script:
- git ls-files './*.json' | xargs packer validate
